apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
  - image: prosenkiewicz/user
    context: user
    sync:
      manual:
        - src: "./user/**/*.go"
          dest: .
    docker:
      dockerfile: Dockerfile
  - image: prosenkiewicz/notification
    context: notification
    sync:
      manual:
        - src: "./notification/**/*.go"
          dest: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl: {}