apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          imagePullPolicy: Never
          image: prosenkiewicz/user
          env:
            - name: "RABBITMQ_HOST"
              value: "rabbitmq-srv"
            - name: "RABBITMQ_PORT"
              value: "5672"
            - name: "RABBITMQ_LOGIN"
              value: "guest"
            - name: "RABBITMQ_USER_QUEUE"
              value: "user-queue"
            - name: "RABBITMQ_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 8080
      targetPort: 8080